# Generated by Django 4.1.3 on 2022-11-26 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitlist', '0002_waiter_referrer'),
    ]

    operations = [
        migrations.AddField(
            model_name='waiter',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
