# Generated by Django 4.1.3 on 2022-11-28 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitlist', '0003_waiter_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='waiter',
            name='waiting',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='waiter',
            name='signup_date',
            field=models.DateTimeField(verbose_name='signup_date'),
        ),
    ]
